### PR TITLE
Fix memory leak: close unused record writers

### PR DESCRIPTION
**Pull request by itwaseasy**
The problem is that record writers never close: approximately every 30 seconds in my case, Camus opens a new file (and writer) for writing data, but the old one remains open until the application terminates.

The fix limits the number of open writers per "topic+leader_id+partition" key to 2 and closes old writers accordingly.

[Prevent possible GC camus failures in advance](https://trello.com/c/BCdGcNAm/22-prevent-possible-gc-camus-failures-in-advance)

### CODE REVIEW

**Comment by itszootime** [comment]
Do you know why Camus opens new files so often? I thought that Camus only opened a new file each time the working filename changes, which should be limited as that uses the format `data.{topic}.{leader}.{partition}.{timestamp rounded to the hour}` - i.e. if we process messages spanning a 2 hour period, shouldn't only 2 files be opened per partition? Here's the related source code in [`EtlMultiOutputRecordWriter`](https://github.com/remerge/camus/blob/eac1a8f508aa812070ae79b07d703f64835d0c95/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputRecordWriter.java) and [`EtlMultiOutputFormat`](https://github.com/remerge/camus/blob/eac1a8f508aa812070ae79b07d703f64835d0c95/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputFormat.java).

Checking the logs of a recent losses_v2 run, it created the expected number of writers (30 partitions * 2 hour = 60):

```
richard@nn2.dw1.remerge.io [0] 15:12:06 ~
$ yarn logs -applicationId application_1656253736816_4652 | grep "Writing to data file" | wc -l
60
```

**Comment by itwaseasy** [comment]
> Do you know why Camus opens new files so often?

Thanks for pointing this out: I start processing the topic from the earliest available offset (26.06 around 17:00 UTC) and it doesn't take that long to process one hour:

```
2022-07-04 11:46:29,427 INFO [main] com.linkedin.camus.etl.kafka.mapred.EtlMultiOutputRecordWriter: Writing to data file: data.losses_v2.6.4.1656262800000, partition: 1656262800000
2022-07-04 11:46:49,496 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new compressor [.gz]
2022-07-04 11:46:49,498 INFO [main] com.linkedin.camus.etl.kafka.mapred.EtlMultiOutputRecordWriter: Writing to data file: data.losses_v2.6.4.1656266400000, partition: 1656266400000
2022-07-04 11:47:14,481 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new compressor [.gz]
2022-07-04 11:47:14,483 INFO [main] com.linkedin.camus.etl.kafka.mapred.EtlMultiOutputRecordWriter: Writing to data file: data.losses_v2.6.4.1656270000000,partition: 1656270000000
```

The problem is probably somewhere else, but it would still be great to merge it.

**Comment by itszootime** [comment]
There is at least one legitimate case for Camus keeping open more than two writers though. This could happen when a partition consumes records sequentially with timestamps varying by the hour, potentially caused by mirror lag on certain clusters/partitions. For example on a single partition:

message `m1` ts=2022-07-04T06:10:00Z uses writer `w1` for file `f1` 2022/07/04/06
message `m2` ts=2022-07-04T07:10:00Z uses writer `w2` for file `f2` 2022/07/04/07
message `m3` ts=2022-07-04T08:10:00Z uses writer `w3` for file `f3` 2022/07/04/08
message `m4` ts=2022-07-04T06:10:00Z uses writer `w4` for file `f1` 2022/07/04/06

`w1` will be closed when `m3` is processed (max 2 open writers), so when `m4` is processed  it'll try to create a new writer for `f1`. I think it would then either fail due to `f1` already existing, or overwrite the data in the existing file?

If the number of open files doesn't actually cause an issue in production, is it worth trying to making this limiting behaviour work for all cases?

**Comment by itwaseasy** [comment]
Unfortunately, `ParquetFileWriter` only has two modes: `CREATE` and `OVERWRITE`. In our case, this means that if this case occurs, we will lose data, which is not what we want.

I'm going to close the PR because it looks like it only fixes an edge case (handling a topic for a longer period of time), plus introduces more problems than it fixes.

Thanks, Richard!

**Pull request closed without merging**
